# Generated by Django 5.2.13 on 2026-04-10 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverytracking',
            name='estimated_arrival',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderentry',
            name='estimated_arrival',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderpool',
            name='dispatched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
