# Generated by Django 5.2.13 on 2026-04-10 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_deliverytracking_estimated_arrival_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderentry',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderentry',
            name='penalty_charged',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='orderentry',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('cancelled_free', 'Cancelled (No Charge)'), ('cancelled_penalty', 'Cancelled (Penalty Applied)')], default='active', max_length=20),
        ),
    ]
