# Generated by Django 4.2.7 on 2026-04-15 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_factory_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderpool',
            name='pool_mode',
            field=models.CharField(choices=[('urgent', 'Fast Track'), ('pool', 'Pool Mode')], default='pool', max_length=10),
        ),
    ]
