# Generated by Django 4.2.7 on 2026-04-15 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_pool_mode_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('total_earned', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
