# Generated by Django 4.2.7 on 2026-04-16 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_wallet_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderentry',
            name='escrow_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
