# Generated by Django 4.2.7 on 2026-04-24 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_razorpay_withdrawal'),
    ]

    operations = [
        migrations.AddField(
            model_name='factory',
            name='gstin',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AddField(
            model_name='factoryorder',
            name='invoice_pdf',
            field=models.FileField(blank=True, null=True, upload_to='invoices/'),
        ),
        migrations.AddField(
            model_name='medicalstore',
            name='gstin',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
    ]
