# Generated by Django 4.2.7 on 2026-04-24 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_gst_invoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='disputes/')),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved_payout', 'Resolved — Payout Released'), ('resolved_refund', 'Resolved — Store Refunded')], default='open', max_length=20)),
                ('raised_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('admin_note', models.CharField(blank=True, max_length=255)),
                ('delivery', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dispute', to='core.deliverytracking')),
            ],
            options={
                'ordering': ['-raised_at'],
            },
        ),
    ]
