# Generated by Django 4.2.7 on 2026-04-28 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_deliverytracking_driver_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='expiry_date',
            field=models.DateField(blank=True, help_text='Batch expiry date. Products within 30 days of expiry are auto-disabled.', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Inactive products are hidden from pools and search. Auto-set False near expiry.'),
        ),
        migrations.AlterField(
            model_name='deliverytracking',
            name='driver_token',
            field=models.CharField(blank=True, default='', help_text='Tokenised auth for the driver PWA. Auto-generated on first save.', max_length=32),
        ),
    ]
