# Generated by Django 4.2.7 on 2026-04-30 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_wallettransaction_audit_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderentry',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('delivered', 'Delivered'), ('cancelled_free', 'Cancelled (No Charge)'), ('cancelled_penalty', 'Cancelled (Penalty Applied)')], default='active', max_length=20),
        ),
    ]
