# Generated by Django 4.2.7 on 2026-05-01 08:46

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_wallettransaction_gateway_fee_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='gateway_fee_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Razorpay 2% gateway fee charged on this transaction. Zero for internal ledger movements.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='gateway_gst_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='18% GST levied on the gateway fee. Zero for internal ledger movements.', max_digits=10),
        ),
    ]
