# Generated by Django 4.2.7 on 2026-05-04 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_deliverytracking_3pl_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverytracking',
            name='logistics_partner',
            field=models.CharField(blank=True, default='', help_text='Provider name, e.g. "Delhivery" or "Shadowfax". Blank for local deliveries.', max_length=100),
        ),
        migrations.AlterField(
            model_name='deliverytracking',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Shipping cost charged by the 3PL provider in ₹. Deducted from the factory's net payout.", max_digits=10),
        ),
    ]
